### ISSUE TITLE
Notifications are flaky in prod (multi worker/server) environment

### ISSUE THREAD

**Issue by AMekss** [bolshakov/stoplight#116]
Hi, thank you for your efforts in providing this library. Recently we started to use it in our production stack and I noticed that notifications works a bit flaky in production while there is no issues in development environment. I suspect that redis store has some race condition issues.

Our environment is multi server rails/unicorn (running 4 workers each), we're using `stoplight` gem version 2.1.3
Initializer looks as follows:
```ruby
require 'stoplight'

redis_store = Redis.new(Rails.application.config_for(:cache_redis))
Stoplight::Light.default_data_store = Stoplight::DataStore::Redis.new(redis_store)

Stoplight::Light.default_notifiers += [
  Metrics::StoplightNotifier,
  Stoplight::Notifier::Logger.new(::Logger.new(STDOUT))
]
```
and we're calling it like this:
``` ruby
Stoplight(message.label) { message.call }
  .with_error_handler { |e| Bugsnag.notify(message.merge_into(e)) }
  .with_fallback { message.fallback }
```

And that's how prod logs looks like:
<img width="1087" alt="screen shot 2018-04-24 at 09 53 12" src="https://user-images.githubusercontent.com/327187/39172813-922a8162-47ab-11e8-9f9f-0de4a4ef7597.png">
As you can see sometimes there are multiple notifications when stoplight goes from green to red and none for when it goes back to green. Sometimes it works alright, probably when the load on system is not that high.

From my brief investigation I think this could be fixed either by using [redis scripting](https://redis.io/topics/transactions#redis-scripting-and-transactions) which is transactional by default according to their docs, but that would mean to depend on at least 2.6 Redis server version or use [WATCH](https://redis.io/commands/watch) when writing and discarding failures. Maybe there is other even better idea on how to fix this as atm I'm not too familiar with the internals of the stoplight gem. wdyt?

**Comment by rawstacktech** [comment]
I've seen the same problem using the in memory store also. 
Essentially, any requests in flight when the light goes red that fail will also 'change' the light to red, thus sending another notification.

**Comment by bolshakov** [comment]
Fixed https://github.com/bolshakov/stoplight/issues/116
