### ISSUE TITLE
Stoplight::Light::Runnable#run_yellow fails when failures cleared

### ISSUE THREAD

**Issue by fabpoeschl** [bolshakov/stoplight#124]
`lib/stoplight/light/runnable.rb#40` does not check for `failures.any?` and thus will fail if `failures == nil`

See following stacktrace from production server:
``` 
NoMethodError: undefined method `empty?' for nil:NilClass
…0/gems/stoplight-2.1.3/lib/stoplight/light/runnable.rb:   40:in `block in run_yellow'
…0/gems/stoplight-2.1.3/lib/stoplight/light/runnable.rb:   53:in `run_code'
…0/gems/stoplight-2.1.3/lib/stoplight/light/runnable.rb:   42:in `run_yellow'
…0/gems/stoplight-2.1.3/lib/stoplight/light/runnable.rb:   24:in `run'
```

**Comment by tfausak** [comment]
As you may have noticed, this repository is not maintained. If you're interested in becoming the maintainer, let me know.

**Comment by Lokideos** [comment]
Hey, @fabpoeschl!
Is this issue still relevant?
