### ISSUE TITLE
Lock light state using the Light class interface

### ISSUE THREAD

**Issue by Lokideos** [bolshakov/stoplight#162]
To manually lock the state of light, we use the `data_store` interface. For example:
```ruby
light = Stoplight('example-locked') { true }
# => #<Stoplight::Light:..>
light.run
# => true
light.data_store.set_state(light, Stoplight::State::LOCKED_RED)
# => "locked_red"
light.run
# Stoplight::Error::RedLight: example-locked
```

However, it allows us to use the interface of one light to lock the state of any other light. To avoid this situation, I'd like to add the `Light#set_state` method, which will be called like this:
```ruby
light = Stoplight('example-locked') { true }
light.set_state(Stoplight::State::LOCKED_RED)
```

This implementation will clearly show for what light we lock the state.

**Comment by bolshakov** [comment]
Maybe instead of emphasizing setting state, we can emphasize locking the circuit breaker:

```ruby 
light = Stoplight('example-locked') { true }
light.lock(Stoplight::Color::RED) 
```

Users don't have to know about the `Stoplight::State::LOCKED_RED` which is internal details aimed to distinguish red statute from locked red. What do you think?

**Comment by Lokideos** [comment]
@bolshakov yes, that's a great idea! I also think that to unlock it, we can just use the `Light#unlock` method without any arguments. WDYT?

**Comment by bolshakov** [comment]
This makes sense to me
